---
# - name: Add linux computer to Active Directory OU using a windows machine
#   microsoft.ad.computer:
#     name: one_linux_server
#     sam_account_name: linux_server$
#     dns_hostname: one_linux_server.my_org.local
#     path: OU=servers,DC=my_org,DC=local
#     description: Example of linux server
#     enabled: true
#     state: present

- name: Change the hostname 
  win_hostname:
    name: "{{ hostname }}"
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required

- name: Join new Windows machine to domain controller with automatic reboot
  microsoft.ad.membership:
    dns_domain_name: "vntechsol.com"
    hostname: "{{ hostname }}"
    domain_admin_user: administrator
    domain_admin_password: "P@ssW0rd123456"
    #domain_ou_path: "OU=Windows,OU=Servers,DC=vntechsol,DC=com"
    state: domain
    reboot: true
  #delegate_to: "{{ delegate_host | default(omit) }}"
  when: inventory_hostname in groups["win"]