---
- name: Setup Windows Domain Controller.
  hosts: all
  gather_facts: false
  collections:
    - community.windows

  roles:
  - windows_domain
  #- { role: windows_domain, tags: windows_domain, when: "inventory_hostname in groups.gets('ad', [])" }
