---
- name: Set upstream DNS server.
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '{{ upstream_dns_1 }}'
    - '{{ upstream_dns_2 }}'

- name: Stop the time service.
  win_service:
    name: w32time
    state: stopped

- name: Set NTP Servers.
  win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ ntp_servers }}"'
  
- name: Start the time service.
  win_service:
    name: w32time
    state: started

- name: Disable Windows local Firewall ready to setup Windows Domain.
  win_firewall:
    profiles:
    - Domain
    - Private
    - Public
    state: disabled

- name: Change the hostname 
  win_hostname:
    name: '{{ dc_hostname }}'
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required

- name: Install Windows Features and Role ready for creating a Windows Domain.
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: True
    include_management_tools: True

- name: Create new domain in a new forest on the target host and reboot.
  win_domain:
    dns_domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ recovery_password }}"
    reboot: True

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'

- name: Create reverse DNS zone
  win_shell: "Add-DnsServerPrimaryZone -NetworkID {{reverse_dns_zone}} -ReplicationScope Forest"  
  retries: 30
  delay: 60
  register: result           
  until: result is succeeded

- name: Check for xRemoteDesktopAdmin Powershell module.
  win_psmodule:
    name: xRemoteDesktopAdmin
    state: present

- name: Enable Remote Desktop.
  win_dsc:
    resource_name: xRemoteDesktopAdmin
    Ensure: present
    UserAuthentication: NonSecure
