---
- name: WinRM connection to a group.
  add_host:
   group: dc_machine 
   name: "{{ dc_ip }}" 
   ansible_connection: winrm

- name: test.
  host: "{{ dc_machine }}"

- name: Disable Windows local Firewall ready to setup Windows Domain.
  win_firewall:
    profiles:
    - Domain
    - Private
    - Public
    state: disabled
  tags: disable_firewall
  delegate_to: "{{ dc_machine }}"

- name: Change the hostname 
  win_hostname:
    name: '{{ dc_hostname }}'
  register: res
  delegate_to: '{{ dc_ip }}'

- name: Reboot
  win_reboot:
  when: res.reboot_required   
  delegate_to: '{{ dc_ip }}'

- name: Install Windows Features and Role ready for creating a Windows Domain.
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: True
    include_management_tools: True
    